### ISSUE TITLE
How do I make a change?

### ISSUE THREAD

**Issue by benlieb** [yury-dymov/redux-object#41]
This library seems only meant for reading. How do you suggest making a change to the object and saving back to the redux store?

**Comment by vitorreis** [comment]
+1 here

**Comment by yury-dymov** [comment]
This is a basic redux question. You are supposed to dispatch a redux action, which is handled by reducer function and apply a desired change to your store. `redux-object` is just a utility, which helps to build JS object from normalized data, and knows very little about your application and storage architecture.

**Comment by benlieb** [comment]
I disagree that this should somehow be seen as obvious. We all know how redux works, else we wouldn't be here. The fact that you have used redux in the name of your library is confusing, there are others even on this issue that feel confused. If your library should have no knowledge of redux, why is redux in the title? Shouldn't it be called normalized-object?

In my case the normalized data that redux-object is building from, has redundant information in it, so it is not obvious to change. For example say that I have a table of people, and people have favorite_restaurants. What if 2 people have the same favorite restaurant id:4, and I want to remove that restaurant from my store. If person1.favorite_restaurant when this data comes from the server favorite_restuaruant is in the restaurant array, but also is referenced by the people who have it as a favorite. My hope was that this library would take care of all of this reference data simply. As it is, it's easier to just post to the server and remove the restaurant and update the store from the server.

**Comment by yury-dymov** [comment]
@benlieb, listen, I didn't try to insult you by saying "basic". My point was that everything what is supported is written in README. Otherwise, I provided a valid answer for the question.

Naming is the most hard problem in CS and I am not going to apologize for picking this name over another. Other folks were able to find it and use for quite some time, so maybe it's not perfect but works.

> In my case the normalized data that redux-object is building from, has redundant information in it, so it is not obvious to change. 

To me this sounds a bit weird. If data is normalized, it shouldn't have redundant information in the first place. In your example with restaurants, I would expect to have three entities: Restaurants, People and PeopleToRestaurants. If somebody removes restaurant from favorites, you would delete one record from the last one and other people would be not affected.
